site_name: Tango V10 Design Document
repo_url: https://github.com/ingvord/tango-v10-design-doc

theme: readthedocs
#theme_dir: 'docs/_theme/tango-cs'

pages:
- Home: index.md
- Client side: client.md
- Server side: server.md